#!/bin/bash

DIR="./"
BITRATE=320
OUTPUT="./output"

while [ $# -gt 0 ]; do
	case $1 in
		-p | --path)
			shift
			DIR=$1
			;;
		-b | --bitrate)
			shift
			BITRATE=$1
			;;
		-o | --output-directory)
			shift
			OUTPUT=$1
			;;
		-h | --help)
			# It gets right path of script, then print help file
			cat $(dirname $(readlink -f $0))/doc/help
			exit 0
			;;
	esac
	shift
done

# return the number of FLAC files founded in path
COUNT=$(ls -1 "${DIR}"/*.flac 2> /dev/null | wc -l)

echo "I'll convert all FLAC files inside $DIR"
echo -e "I've found $COUNT FLAC files to convert\n" 
if [ $COUNT -gt 0 ]; then
	
	# create directory output or nested directory output and set permissions
	if ! [ -d "$OUTPUT" ]; then mkdir -p "$OUTPUT"; fi
	if ! [ -w "$OUTPUT" ]; then chmod u+x "$OUTPUT"; fi

	# use avconv (ffmpeg) to convert each file
	# OPTION -threads auto (use multithreading if it is possible)
	for name in "${DIR}"/*.flac ; do
    	avconv -threads auto -i "$name" -vn -b:a ${BITRATE}k -strict -2 "$OUTPUT"/"$(basename "${name/.flac}").m4a"
	done

else
	echo -e "Sorry, FLAC files not found in this directory\n"
fi

echo "Done!"
exit 0
